use_frameworks!

def my_pods
	inhibit_all_warnings!
  pod 'RxSwift'
  pod 'SwiftyJSON'
  pod 'Gifu'
end

target 'iGif' do
  my_pods
end

target 'iGifTests' do
  my_pods
	inhibit_all_warnings!
  pod 'Nimble'
  pod 'RxNimble'
  pod 'RxBlocking'
  pod 'OHHTTPStubs'
  pod 'OHHTTPStubs/Swift'
end
